services:
  hugo:
    # image: hugomods/hugo:exts-0.136.5
    image: hugomods/hugo:exts-0.152.2
    container_name: hugo-dev
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    working_dir: /src
    command: hugo server --bind 0.0.0.0 --port 1313 --buildDrafts --buildFuture --renderToMemory