baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Bulsara'
theme = 'Bulsara-theme'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Sobre Nosotros"
    url = "/about-us/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "photos"
    name = "Fotos"
    url = "/photo-album/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contact-us/"
    weight = 5

[params]
contactUsText = "Cont√°ctanos"
facebookLink = "https://facebook.com/bulsara"
instagramLink = "https://instagram.com/bulsara"

